name = "spinogambino-avis-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-avis.fr"
HMAC_KEY = "208277b25429b4b39e499fbc5cfdb069070a83649b3a80dd945fc36892061aac"
COOKIE_NAME = "skq"
PLAY_PATH = "start-now"
BUTTON_ID = "pd270c60be88fcbe77ba29b2292d41f95"
GATE_SALT = "5dab3768416a11ea"
